### PR TITLE
Slideshow support

### PR DESCRIPTION
**Pull request by sinistersnare**
this PR uses reveal.js to generate slideshows for each meetup. 

The new meetup.com description formatting is as follows:
```
Presenter1 title
Presenter1 Paragraph1
Presenter1 ParagraphN
-----
Presenter2 title
Presenter2 Paragraph1
Presenter2 ParagraphN
```
note the **5** dashes. This is so we can have arbitrary amounts of description paragraphs. Also titles may be shortened to "January 2015 Meetup". You will see why in the screenshots :D

This is a pretty big dependency, ~100Kb. well, it is compared to 0Kb. I chose reveal.js because I looked for other alternatives with a nice "API" and they only supported pictures. Also reveal has good themeing support, if we do not like the default.

***ANY COMMENTS QUESTIONS CONCERNS WELCOME***

CC @dgreisen, also would you mind updating the debug fixtures, I do not know how to.

**TODO:**

- [ ] Only allow this for presentation meetups
- [ ] Clean up code
- [ ] Find a theme that works better (if that is needed)
- [ ] Implement new description formatting for meetup.com 
- [ ] Style "see slides!" on the event-detail page

### CODE REVIEW

**Comment by dgreisen** [comment]
Hi all,

Sorry for the radio silence. I think this is a hugely beneficial feature. I want us to have a custom slide deck for each meetup. I think it shows respect to our speakers to have an introductory slide show that actually mentions them rather than a generic slide deck.  It's also just generally slick.

We can minimize confusion through ux, naming, etc. I'll look into the implementation now and make any suggestions.

**Comment by edwelker** [comment]
@dgreisen please describe the intent a little more.  I want to consider it.

That said, I'm generally against any introductory slide deck, for a multitude of reasons.  Generally, it takes focus away from the speaker presentations.  Specifically, it disrupts speaker setup, subtly slows down the meetup, it doesn't convey anything that the host can't audibly convey more personally, the visuals distract from people interacting with (from discussion, to turning their head to look at) other attendees/speakers/sponsors, etc.

**Comment by aclark4life** [comment]
FWIW, I am of course in favor of a generic slide show before each meetup: http://www.slideshare.net/dcpython/generic-meetup-slides. I think it's important to (visually) pimp the DC Python "brand" before each meeting, if nothing else.

**Comment by sinistersnare** [comment]
how a meetup goes in my head:

1. People enter, begin meetup time
2. Person in charge of meetup is at front with these slides up
3. Speaker introduces DCPython, what it is, and when.
4. Next is the host, ask if they have someone to promote their business
5. Finally is the main speakers, listed in order of speaking.
6. first speaker comes up and sets up.

Im not sure if there is anything else needed in there, but it should be quick, like <5 minutes, because people who come every month will know the drill eventually :)

Looking at the images again, I have thoughts about how it could look a bit better, but I am ***NOT*** a UX designer in any way!

**Pull request closed without merging**
